// Code generated by protoc-gen-go. DO NOT EDIT.
// source: faceAPI.proto

package xgfaceAPI

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Images struct {
	Image1               string   `protobuf:"bytes,1,opt,name=image1,proto3" json:"image1,omitempty"`
	Image2               string   `protobuf:"bytes,2,opt,name=image2,proto3" json:"image2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Images) Reset()         { *m = Images{} }
func (m *Images) String() string { return proto.CompactTextString(m) }
func (*Images) ProtoMessage()    {}
func (*Images) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{1}
}

func (m *Images) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Images.Unmarshal(m, b)
}
func (m *Images) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Images.Marshal(b, m, deterministic)
}
func (m *Images) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Images.Merge(m, src)
}
func (m *Images) XXX_Size() int {
	return xxx_messageInfo_Images.Size(m)
}
func (m *Images) XXX_DiscardUnknown() {
	xxx_messageInfo_Images.DiscardUnknown(m)
}

var xxx_messageInfo_Images proto.InternalMessageInfo

func (m *Images) GetImage1() string {
	if m != nil {
		return m.Image1
	}
	return ""
}

func (m *Images) GetImage2() string {
	if m != nil {
		return m.Image2
	}
	return ""
}

type FaceField struct {
	Landmark             int32    `protobuf:"varint,1,opt,name=landmark,proto3" json:"landmark,omitempty"`
	Attributes           int32    `protobuf:"varint,2,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Quality              int32    `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"`
	Feature              int32    `protobuf:"varint,4,opt,name=feature,proto3" json:"feature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FaceField) Reset()         { *m = FaceField{} }
func (m *FaceField) String() string { return proto.CompactTextString(m) }
func (*FaceField) ProtoMessage()    {}
func (*FaceField) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{2}
}

func (m *FaceField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaceField.Unmarshal(m, b)
}
func (m *FaceField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaceField.Marshal(b, m, deterministic)
}
func (m *FaceField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaceField.Merge(m, src)
}
func (m *FaceField) XXX_Size() int {
	return xxx_messageInfo_FaceField.Size(m)
}
func (m *FaceField) XXX_DiscardUnknown() {
	xxx_messageInfo_FaceField.DiscardUnknown(m)
}

var xxx_messageInfo_FaceField proto.InternalMessageInfo

func (m *FaceField) GetLandmark() int32 {
	if m != nil {
		return m.Landmark
	}
	return 0
}

func (m *FaceField) GetAttributes() int32 {
	if m != nil {
		return m.Attributes
	}
	return 0
}

func (m *FaceField) GetQuality() int32 {
	if m != nil {
		return m.Quality
	}
	return 0
}

func (m *FaceField) GetFeature() int32 {
	if m != nil {
		return m.Feature
	}
	return 0
}

type DetectReq struct {
	Facefield            *FaceField `protobuf:"bytes,1,opt,name=facefield,proto3" json:"facefield,omitempty"`
	Images               []string   `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DetectReq) Reset()         { *m = DetectReq{} }
func (m *DetectReq) String() string { return proto.CompactTextString(m) }
func (*DetectReq) ProtoMessage()    {}
func (*DetectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{3}
}

func (m *DetectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectReq.Unmarshal(m, b)
}
func (m *DetectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectReq.Marshal(b, m, deterministic)
}
func (m *DetectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectReq.Merge(m, src)
}
func (m *DetectReq) XXX_Size() int {
	return xxx_messageInfo_DetectReq.Size(m)
}
func (m *DetectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectReq.DiscardUnknown(m)
}

var xxx_messageInfo_DetectReq proto.InternalMessageInfo

func (m *DetectReq) GetFacefield() *FaceField {
	if m != nil {
		return m.Facefield
	}
	return nil
}

func (m *DetectReq) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

type Point struct {
	CoordinateX          float32  `protobuf:"fixed32,1,opt,name=coordinate_x,json=coordinateX,proto3" json:"coordinate_x,omitempty"`
	CoordinateY          float32  `protobuf:"fixed32,2,opt,name=coordinate_y,json=coordinateY,proto3" json:"coordinate_y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{4}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetCoordinateX() float32 {
	if m != nil {
		return m.CoordinateX
	}
	return 0
}

func (m *Point) GetCoordinateY() float32 {
	if m != nil {
		return m.CoordinateY
	}
	return 0
}

type Rect struct {
	Width                float32  `protobuf:"fixed32,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               float32  `protobuf:"fixed32,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rect) Reset()         { *m = Rect{} }
func (m *Rect) String() string { return proto.CompactTextString(m) }
func (*Rect) ProtoMessage()    {}
func (*Rect) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{5}
}

func (m *Rect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rect.Unmarshal(m, b)
}
func (m *Rect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rect.Marshal(b, m, deterministic)
}
func (m *Rect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rect.Merge(m, src)
}
func (m *Rect) XXX_Size() int {
	return xxx_messageInfo_Rect.Size(m)
}
func (m *Rect) XXX_DiscardUnknown() {
	xxx_messageInfo_Rect.DiscardUnknown(m)
}

var xxx_messageInfo_Rect proto.InternalMessageInfo

func (m *Rect) GetWidth() float32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Rect) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Feature struct {
	Values               []float32 `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{6}
}

func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (m *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(m, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

func (m *Feature) GetValues() []float32 {
	if m != nil {
		return m.Values
	}
	return nil
}

type Features struct {
	Features             []*Feature `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Features) Reset()         { *m = Features{} }
func (m *Features) String() string { return proto.CompactTextString(m) }
func (*Features) ProtoMessage()    {}
func (*Features) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{7}
}

func (m *Features) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Features.Unmarshal(m, b)
}
func (m *Features) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Features.Marshal(b, m, deterministic)
}
func (m *Features) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Features.Merge(m, src)
}
func (m *Features) XXX_Size() int {
	return xxx_messageInfo_Features.Size(m)
}
func (m *Features) XXX_DiscardUnknown() {
	xxx_messageInfo_Features.DiscardUnknown(m)
}

var xxx_messageInfo_Features proto.InternalMessageInfo

func (m *Features) GetFeatures() []*Feature {
	if m != nil {
		return m.Features
	}
	return nil
}

type Box struct {
	Center               *Point   `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	Rect                 *Rect    `protobuf:"bytes,2,opt,name=rect,proto3" json:"rect,omitempty"`
	Score                float32  `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Box) Reset()         { *m = Box{} }
func (m *Box) String() string { return proto.CompactTextString(m) }
func (*Box) ProtoMessage()    {}
func (*Box) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{8}
}

func (m *Box) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Box.Unmarshal(m, b)
}
func (m *Box) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Box.Marshal(b, m, deterministic)
}
func (m *Box) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Box.Merge(m, src)
}
func (m *Box) XXX_Size() int {
	return xxx_messageInfo_Box.Size(m)
}
func (m *Box) XXX_DiscardUnknown() {
	xxx_messageInfo_Box.DiscardUnknown(m)
}

var xxx_messageInfo_Box proto.InternalMessageInfo

func (m *Box) GetCenter() *Point {
	if m != nil {
		return m.Center
	}
	return nil
}

func (m *Box) GetRect() *Rect {
	if m != nil {
		return m.Rect
	}
	return nil
}

func (m *Box) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

type Boxs struct {
	Boxs                 []*Box   `protobuf:"bytes,1,rep,name=boxs,proto3" json:"boxs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Boxs) Reset()         { *m = Boxs{} }
func (m *Boxs) String() string { return proto.CompactTextString(m) }
func (*Boxs) ProtoMessage()    {}
func (*Boxs) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{9}
}

func (m *Boxs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Boxs.Unmarshal(m, b)
}
func (m *Boxs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Boxs.Marshal(b, m, deterministic)
}
func (m *Boxs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Boxs.Merge(m, src)
}
func (m *Boxs) XXX_Size() int {
	return xxx_messageInfo_Boxs.Size(m)
}
func (m *Boxs) XXX_DiscardUnknown() {
	xxx_messageInfo_Boxs.DiscardUnknown(m)
}

var xxx_messageInfo_Boxs proto.InternalMessageInfo

func (m *Boxs) GetBoxs() []*Box {
	if m != nil {
		return m.Boxs
	}
	return nil
}

type Landmark struct {
	Points               []*Point `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	Score                float32  `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Landmark) Reset()         { *m = Landmark{} }
func (m *Landmark) String() string { return proto.CompactTextString(m) }
func (*Landmark) ProtoMessage()    {}
func (*Landmark) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{10}
}

func (m *Landmark) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Landmark.Unmarshal(m, b)
}
func (m *Landmark) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Landmark.Marshal(b, m, deterministic)
}
func (m *Landmark) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Landmark.Merge(m, src)
}
func (m *Landmark) XXX_Size() int {
	return xxx_messageInfo_Landmark.Size(m)
}
func (m *Landmark) XXX_DiscardUnknown() {
	xxx_messageInfo_Landmark.DiscardUnknown(m)
}

var xxx_messageInfo_Landmark proto.InternalMessageInfo

func (m *Landmark) GetPoints() []*Point {
	if m != nil {
		return m.Points
	}
	return nil
}

func (m *Landmark) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

type Landmarks struct {
	Landmarks            []*Landmark `protobuf:"bytes,1,rep,name=landmarks,proto3" json:"landmarks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Landmarks) Reset()         { *m = Landmarks{} }
func (m *Landmarks) String() string { return proto.CompactTextString(m) }
func (*Landmarks) ProtoMessage()    {}
func (*Landmarks) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{11}
}

func (m *Landmarks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Landmarks.Unmarshal(m, b)
}
func (m *Landmarks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Landmarks.Marshal(b, m, deterministic)
}
func (m *Landmarks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Landmarks.Merge(m, src)
}
func (m *Landmarks) XXX_Size() int {
	return xxx_messageInfo_Landmarks.Size(m)
}
func (m *Landmarks) XXX_DiscardUnknown() {
	xxx_messageInfo_Landmarks.DiscardUnknown(m)
}

var xxx_messageInfo_Landmarks proto.InternalMessageInfo

func (m *Landmarks) GetLandmarks() []*Landmark {
	if m != nil {
		return m.Landmarks
	}
	return nil
}

type Body struct {
	Box                  *Box     `protobuf:"bytes,1,opt,name=box,proto3" json:"box,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Body) Reset()         { *m = Body{} }
func (m *Body) String() string { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()    {}
func (*Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{12}
}

func (m *Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Body.Unmarshal(m, b)
}
func (m *Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Body.Marshal(b, m, deterministic)
}
func (m *Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Body.Merge(m, src)
}
func (m *Body) XXX_Size() int {
	return xxx_messageInfo_Body.Size(m)
}
func (m *Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Body proto.InternalMessageInfo

func (m *Body) GetBox() *Box {
	if m != nil {
		return m.Box
	}
	return nil
}

type BodyInfo struct {
	Bodys                []*Body  `protobuf:"bytes,1,rep,name=bodys,proto3" json:"bodys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BodyInfo) Reset()         { *m = BodyInfo{} }
func (m *BodyInfo) String() string { return proto.CompactTextString(m) }
func (*BodyInfo) ProtoMessage()    {}
func (*BodyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{13}
}

func (m *BodyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BodyInfo.Unmarshal(m, b)
}
func (m *BodyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BodyInfo.Marshal(b, m, deterministic)
}
func (m *BodyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BodyInfo.Merge(m, src)
}
func (m *BodyInfo) XXX_Size() int {
	return xxx_messageInfo_BodyInfo.Size(m)
}
func (m *BodyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BodyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BodyInfo proto.InternalMessageInfo

func (m *BodyInfo) GetBodys() []*Body {
	if m != nil {
		return m.Bodys
	}
	return nil
}

type Face struct {
	Box                  *Box             `protobuf:"bytes,1,opt,name=box,proto3" json:"box,omitempty"`
	Landmark             *Landmark        `protobuf:"bytes,2,opt,name=landmark,proto3" json:"landmark,omitempty"`
	Feature              *Feature         `protobuf:"bytes,3,opt,name=feature,proto3" json:"feature,omitempty"`
	Attributes           map[string]int32 `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Pitch                float32          `protobuf:"fixed32,5,opt,name=pitch,proto3" json:"pitch,omitempty"`
	Yaw                  float32          `protobuf:"fixed32,6,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Roll                 float32          `protobuf:"fixed32,7,opt,name=roll,proto3" json:"roll,omitempty"`
	GlobalIsFace         float32          `protobuf:"fixed32,8,opt,name=global_is_face,json=globalIsFace,proto3" json:"global_is_face,omitempty"`
	GlobalFrontFace      float32          `protobuf:"fixed32,9,opt,name=global_front_face,json=globalFrontFace,proto3" json:"global_front_face,omitempty"`
	LocalIsFace          float32          `protobuf:"fixed32,10,opt,name=local_is_face,json=localIsFace,proto3" json:"local_is_face,omitempty"`
	FaceToken            string           `protobuf:"bytes,11,opt,name=faceToken,proto3" json:"faceToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Face) Reset()         { *m = Face{} }
func (m *Face) String() string { return proto.CompactTextString(m) }
func (*Face) ProtoMessage()    {}
func (*Face) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{14}
}

func (m *Face) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Face.Unmarshal(m, b)
}
func (m *Face) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Face.Marshal(b, m, deterministic)
}
func (m *Face) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Face.Merge(m, src)
}
func (m *Face) XXX_Size() int {
	return xxx_messageInfo_Face.Size(m)
}
func (m *Face) XXX_DiscardUnknown() {
	xxx_messageInfo_Face.DiscardUnknown(m)
}

var xxx_messageInfo_Face proto.InternalMessageInfo

func (m *Face) GetBox() *Box {
	if m != nil {
		return m.Box
	}
	return nil
}

func (m *Face) GetLandmark() *Landmark {
	if m != nil {
		return m.Landmark
	}
	return nil
}

func (m *Face) GetFeature() *Feature {
	if m != nil {
		return m.Feature
	}
	return nil
}

func (m *Face) GetAttributes() map[string]int32 {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Face) GetPitch() float32 {
	if m != nil {
		return m.Pitch
	}
	return 0
}

func (m *Face) GetYaw() float32 {
	if m != nil {
		return m.Yaw
	}
	return 0
}

func (m *Face) GetRoll() float32 {
	if m != nil {
		return m.Roll
	}
	return 0
}

func (m *Face) GetGlobalIsFace() float32 {
	if m != nil {
		return m.GlobalIsFace
	}
	return 0
}

func (m *Face) GetGlobalFrontFace() float32 {
	if m != nil {
		return m.GlobalFrontFace
	}
	return 0
}

func (m *Face) GetLocalIsFace() float32 {
	if m != nil {
		return m.LocalIsFace
	}
	return 0
}

func (m *Face) GetFaceToken() string {
	if m != nil {
		return m.FaceToken
	}
	return ""
}

type DetectInfo struct {
	FaceNum              int32    `protobuf:"varint,1,opt,name=faceNum,proto3" json:"faceNum,omitempty"`
	Faces                []*Face  `protobuf:"bytes,2,rep,name=faces,proto3" json:"faces,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetectInfo) Reset()         { *m = DetectInfo{} }
func (m *DetectInfo) String() string { return proto.CompactTextString(m) }
func (*DetectInfo) ProtoMessage()    {}
func (*DetectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{15}
}

func (m *DetectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectInfo.Unmarshal(m, b)
}
func (m *DetectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectInfo.Marshal(b, m, deterministic)
}
func (m *DetectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectInfo.Merge(m, src)
}
func (m *DetectInfo) XXX_Size() int {
	return xxx_messageInfo_DetectInfo.Size(m)
}
func (m *DetectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DetectInfo proto.InternalMessageInfo

func (m *DetectInfo) GetFaceNum() int32 {
	if m != nil {
		return m.FaceNum
	}
	return 0
}

func (m *DetectInfo) GetFaces() []*Face {
	if m != nil {
		return m.Faces
	}
	return nil
}

// 人脸检测返回值
type DetectResp struct {
	ErrCode              int32       `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string      `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	DetectInfo           *DetectInfo `protobuf:"bytes,3,opt,name=detectInfo,proto3" json:"detectInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DetectResp) Reset()         { *m = DetectResp{} }
func (m *DetectResp) String() string { return proto.CompactTextString(m) }
func (*DetectResp) ProtoMessage()    {}
func (*DetectResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{16}
}

func (m *DetectResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectResp.Unmarshal(m, b)
}
func (m *DetectResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectResp.Marshal(b, m, deterministic)
}
func (m *DetectResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectResp.Merge(m, src)
}
func (m *DetectResp) XXX_Size() int {
	return xxx_messageInfo_DetectResp.Size(m)
}
func (m *DetectResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectResp.DiscardUnknown(m)
}

var xxx_messageInfo_DetectResp proto.InternalMessageInfo

func (m *DetectResp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *DetectResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *DetectResp) GetDetectInfo() *DetectInfo {
	if m != nil {
		return m.DetectInfo
	}
	return nil
}

// 人脸比对
type Image struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{17}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ScoreResp struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	Score                float32  `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScoreResp) Reset()         { *m = ScoreResp{} }
func (m *ScoreResp) String() string { return proto.CompactTextString(m) }
func (*ScoreResp) ProtoMessage()    {}
func (*ScoreResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{18}
}

func (m *ScoreResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScoreResp.Unmarshal(m, b)
}
func (m *ScoreResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScoreResp.Marshal(b, m, deterministic)
}
func (m *ScoreResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScoreResp.Merge(m, src)
}
func (m *ScoreResp) XXX_Size() int {
	return xxx_messageInfo_ScoreResp.Size(m)
}
func (m *ScoreResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ScoreResp.DiscardUnknown(m)
}

var xxx_messageInfo_ScoreResp proto.InternalMessageInfo

func (m *ScoreResp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *ScoreResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *ScoreResp) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

// 以下为注册人脸专用信息
type AddFaceReq struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	UserInfo             string   `protobuf:"bytes,3,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFaceReq) Reset()         { *m = AddFaceReq{} }
func (m *AddFaceReq) String() string { return proto.CompactTextString(m) }
func (*AddFaceReq) ProtoMessage()    {}
func (*AddFaceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{19}
}

func (m *AddFaceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFaceReq.Unmarshal(m, b)
}
func (m *AddFaceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFaceReq.Marshal(b, m, deterministic)
}
func (m *AddFaceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFaceReq.Merge(m, src)
}
func (m *AddFaceReq) XXX_Size() int {
	return xxx_messageInfo_AddFaceReq.Size(m)
}
func (m *AddFaceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFaceReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddFaceReq proto.InternalMessageInfo

func (m *AddFaceReq) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *AddFaceReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *AddFaceReq) GetUserInfo() string {
	if m != nil {
		return m.UserInfo
	}
	return ""
}

type AddFaceResp struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	Location             *Box     `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	FaceToken            string   `protobuf:"bytes,4,opt,name=faceToken,proto3" json:"faceToken,omitempty"`
	ImgToken             string   `protobuf:"bytes,5,opt,name=imgToken,proto3" json:"imgToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFaceResp) Reset()         { *m = AddFaceResp{} }
func (m *AddFaceResp) String() string { return proto.CompactTextString(m) }
func (*AddFaceResp) ProtoMessage()    {}
func (*AddFaceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{20}
}

func (m *AddFaceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFaceResp.Unmarshal(m, b)
}
func (m *AddFaceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFaceResp.Marshal(b, m, deterministic)
}
func (m *AddFaceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFaceResp.Merge(m, src)
}
func (m *AddFaceResp) XXX_Size() int {
	return xxx_messageInfo_AddFaceResp.Size(m)
}
func (m *AddFaceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFaceResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddFaceResp proto.InternalMessageInfo

func (m *AddFaceResp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *AddFaceResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *AddFaceResp) GetLocation() *Box {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *AddFaceResp) GetFaceToken() string {
	if m != nil {
		return m.FaceToken
	}
	return ""
}

func (m *AddFaceResp) GetImgToken() string {
	if m != nil {
		return m.ImgToken
	}
	return ""
}

// 以下为1：N专用
type ScanResp struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	Score                float32  `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	ImgToken             string   `protobuf:"bytes,4,opt,name=imgToken,proto3" json:"imgToken,omitempty"`
	FaceToken            string   `protobuf:"bytes,5,opt,name=faceToken,proto3" json:"faceToken,omitempty"`
	UserID               string   `protobuf:"bytes,6,opt,name=userID,proto3" json:"userID,omitempty"`
	UserInfo             string   `protobuf:"bytes,7,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanResp) Reset()         { *m = ScanResp{} }
func (m *ScanResp) String() string { return proto.CompactTextString(m) }
func (*ScanResp) ProtoMessage()    {}
func (*ScanResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{21}
}

func (m *ScanResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanResp.Unmarshal(m, b)
}
func (m *ScanResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanResp.Marshal(b, m, deterministic)
}
func (m *ScanResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanResp.Merge(m, src)
}
func (m *ScanResp) XXX_Size() int {
	return xxx_messageInfo_ScanResp.Size(m)
}
func (m *ScanResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanResp.DiscardUnknown(m)
}

var xxx_messageInfo_ScanResp proto.InternalMessageInfo

func (m *ScanResp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *ScanResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *ScanResp) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *ScanResp) GetImgToken() string {
	if m != nil {
		return m.ImgToken
	}
	return ""
}

func (m *ScanResp) GetFaceToken() string {
	if m != nil {
		return m.FaceToken
	}
	return ""
}

func (m *ScanResp) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ScanResp) GetUserInfo() string {
	if m != nil {
		return m.UserInfo
	}
	return ""
}

// 以下信息为M:N接口专用
type ScanFace struct {
	FaceToken            string   `protobuf:"bytes,1,opt,name=faceToken,proto3" json:"faceToken,omitempty"`
	Score                float32  `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	ImgToken             string   `protobuf:"bytes,3,opt,name=imgToken,proto3" json:"imgToken,omitempty"`
	UserID               string   `protobuf:"bytes,4,opt,name=userID,proto3" json:"userID,omitempty"`
	UserInfo             string   `protobuf:"bytes,5,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	Location             *Box     `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanFace) Reset()         { *m = ScanFace{} }
func (m *ScanFace) String() string { return proto.CompactTextString(m) }
func (*ScanFace) ProtoMessage()    {}
func (*ScanFace) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{22}
}

func (m *ScanFace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanFace.Unmarshal(m, b)
}
func (m *ScanFace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanFace.Marshal(b, m, deterministic)
}
func (m *ScanFace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanFace.Merge(m, src)
}
func (m *ScanFace) XXX_Size() int {
	return xxx_messageInfo_ScanFace.Size(m)
}
func (m *ScanFace) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanFace.DiscardUnknown(m)
}

var xxx_messageInfo_ScanFace proto.InternalMessageInfo

func (m *ScanFace) GetFaceToken() string {
	if m != nil {
		return m.FaceToken
	}
	return ""
}

func (m *ScanFace) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *ScanFace) GetImgToken() string {
	if m != nil {
		return m.ImgToken
	}
	return ""
}

func (m *ScanFace) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ScanFace) GetUserInfo() string {
	if m != nil {
		return m.UserInfo
	}
	return ""
}

func (m *ScanFace) GetLocation() *Box {
	if m != nil {
		return m.Location
	}
	return nil
}

type Result struct {
	FaceNum              int32       `protobuf:"varint,1,opt,name=faceNum,proto3" json:"faceNum,omitempty"`
	FaceList             []*ScanFace `protobuf:"bytes,2,rep,name=faceList,proto3" json:"faceList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{23}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetFaceNum() int32 {
	if m != nil {
		return m.FaceNum
	}
	return 0
}

func (m *Result) GetFaceList() []*ScanFace {
	if m != nil {
		return m.FaceList
	}
	return nil
}

type ScanRespEx struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	ScanResult           *Result  `protobuf:"bytes,3,opt,name=scanResult,proto3" json:"scanResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanRespEx) Reset()         { *m = ScanRespEx{} }
func (m *ScanRespEx) String() string { return proto.CompactTextString(m) }
func (*ScanRespEx) ProtoMessage()    {}
func (*ScanRespEx) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{24}
}

func (m *ScanRespEx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanRespEx.Unmarshal(m, b)
}
func (m *ScanRespEx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanRespEx.Marshal(b, m, deterministic)
}
func (m *ScanRespEx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanRespEx.Merge(m, src)
}
func (m *ScanRespEx) XXX_Size() int {
	return xxx_messageInfo_ScanRespEx.Size(m)
}
func (m *ScanRespEx) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanRespEx.DiscardUnknown(m)
}

var xxx_messageInfo_ScanRespEx proto.InternalMessageInfo

func (m *ScanRespEx) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *ScanRespEx) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *ScanRespEx) GetScanResult() *Result {
	if m != nil {
		return m.ScanResult
	}
	return nil
}

// 以下信息为获取人脸列表专用
type ListFaceReq struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFaceReq) Reset()         { *m = ListFaceReq{} }
func (m *ListFaceReq) String() string { return proto.CompactTextString(m) }
func (*ListFaceReq) ProtoMessage()    {}
func (*ListFaceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{25}
}

func (m *ListFaceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFaceReq.Unmarshal(m, b)
}
func (m *ListFaceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFaceReq.Marshal(b, m, deterministic)
}
func (m *ListFaceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFaceReq.Merge(m, src)
}
func (m *ListFaceReq) XXX_Size() int {
	return xxx_messageInfo_ListFaceReq.Size(m)
}
func (m *ListFaceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFaceReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListFaceReq proto.InternalMessageInfo

func (m *ListFaceReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type SingleRecord struct {
	CreateTime           int64    `protobuf:"varint,1,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int64    `protobuf:"varint,2,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	ImgToken             string   `protobuf:"bytes,3,opt,name=imgToken,proto3" json:"imgToken,omitempty"`
	FaceToken            string   `protobuf:"bytes,4,opt,name=faceToken,proto3" json:"faceToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleRecord) Reset()         { *m = SingleRecord{} }
func (m *SingleRecord) String() string { return proto.CompactTextString(m) }
func (*SingleRecord) ProtoMessage()    {}
func (*SingleRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{26}
}

func (m *SingleRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleRecord.Unmarshal(m, b)
}
func (m *SingleRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleRecord.Marshal(b, m, deterministic)
}
func (m *SingleRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleRecord.Merge(m, src)
}
func (m *SingleRecord) XXX_Size() int {
	return xxx_messageInfo_SingleRecord.Size(m)
}
func (m *SingleRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleRecord.DiscardUnknown(m)
}

var xxx_messageInfo_SingleRecord proto.InternalMessageInfo

func (m *SingleRecord) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *SingleRecord) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *SingleRecord) GetImgToken() string {
	if m != nil {
		return m.ImgToken
	}
	return ""
}

func (m *SingleRecord) GetFaceToken() string {
	if m != nil {
		return m.FaceToken
	}
	return ""
}

type ListFaceResp struct {
	ErrCode              int32           `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string          `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	FaceRecord           []*SingleRecord `protobuf:"bytes,3,rep,name=faceRecord,proto3" json:"faceRecord,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListFaceResp) Reset()         { *m = ListFaceResp{} }
func (m *ListFaceResp) String() string { return proto.CompactTextString(m) }
func (*ListFaceResp) ProtoMessage()    {}
func (*ListFaceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{27}
}

func (m *ListFaceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFaceResp.Unmarshal(m, b)
}
func (m *ListFaceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFaceResp.Marshal(b, m, deterministic)
}
func (m *ListFaceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFaceResp.Merge(m, src)
}
func (m *ListFaceResp) XXX_Size() int {
	return xxx_messageInfo_ListFaceResp.Size(m)
}
func (m *ListFaceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFaceResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListFaceResp proto.InternalMessageInfo

func (m *ListFaceResp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *ListFaceResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *ListFaceResp) GetFaceRecord() []*SingleRecord {
	if m != nil {
		return m.FaceRecord
	}
	return nil
}

// 以下信息为删除人脸专用
type DelFaceReq struct {
	FaceToken            string   `protobuf:"bytes,1,opt,name=faceToken,proto3" json:"faceToken,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelFaceReq) Reset()         { *m = DelFaceReq{} }
func (m *DelFaceReq) String() string { return proto.CompactTextString(m) }
func (*DelFaceReq) ProtoMessage()    {}
func (*DelFaceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{28}
}

func (m *DelFaceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelFaceReq.Unmarshal(m, b)
}
func (m *DelFaceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelFaceReq.Marshal(b, m, deterministic)
}
func (m *DelFaceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelFaceReq.Merge(m, src)
}
func (m *DelFaceReq) XXX_Size() int {
	return xxx_messageInfo_DelFaceReq.Size(m)
}
func (m *DelFaceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelFaceReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelFaceReq proto.InternalMessageInfo

func (m *DelFaceReq) GetFaceToken() string {
	if m != nil {
		return m.FaceToken
	}
	return ""
}

func (m *DelFaceReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type DelFaceResp struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelFaceResp) Reset()         { *m = DelFaceResp{} }
func (m *DelFaceResp) String() string { return proto.CompactTextString(m) }
func (*DelFaceResp) ProtoMessage()    {}
func (*DelFaceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{29}
}

func (m *DelFaceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelFaceResp.Unmarshal(m, b)
}
func (m *DelFaceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelFaceResp.Marshal(b, m, deterministic)
}
func (m *DelFaceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelFaceResp.Merge(m, src)
}
func (m *DelFaceResp) XXX_Size() int {
	return xxx_messageInfo_DelFaceResp.Size(m)
}
func (m *DelFaceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelFaceResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelFaceResp proto.InternalMessageInfo

func (m *DelFaceResp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *DelFaceResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// 查询用户信息
type GetUserInfoReq struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoReq) Reset()         { *m = GetUserInfoReq{} }
func (m *GetUserInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoReq) ProtoMessage()    {}
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{30}
}

func (m *GetUserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoReq.Unmarshal(m, b)
}
func (m *GetUserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoReq.Marshal(b, m, deterministic)
}
func (m *GetUserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoReq.Merge(m, src)
}
func (m *GetUserInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoReq.Size(m)
}
func (m *GetUserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoReq proto.InternalMessageInfo

func (m *GetUserInfoReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetUserInfoResp struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	UserInfo             []string `protobuf:"bytes,3,rep,name=userInfo,proto3" json:"userInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoResp) Reset()         { *m = GetUserInfoResp{} }
func (m *GetUserInfoResp) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoResp) ProtoMessage()    {}
func (*GetUserInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{31}
}

func (m *GetUserInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoResp.Unmarshal(m, b)
}
func (m *GetUserInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoResp.Marshal(b, m, deterministic)
}
func (m *GetUserInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoResp.Merge(m, src)
}
func (m *GetUserInfoResp) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoResp.Size(m)
}
func (m *GetUserInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoResp proto.InternalMessageInfo

func (m *GetUserInfoResp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *GetUserInfoResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *GetUserInfoResp) GetUserInfo() []string {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

// 删除用户
type DelUserReq struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelUserReq) Reset()         { *m = DelUserReq{} }
func (m *DelUserReq) String() string { return proto.CompactTextString(m) }
func (*DelUserReq) ProtoMessage()    {}
func (*DelUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{32}
}

func (m *DelUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelUserReq.Unmarshal(m, b)
}
func (m *DelUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelUserReq.Marshal(b, m, deterministic)
}
func (m *DelUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelUserReq.Merge(m, src)
}
func (m *DelUserReq) XXX_Size() int {
	return xxx_messageInfo_DelUserReq.Size(m)
}
func (m *DelUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelUserReq proto.InternalMessageInfo

func (m *DelUserReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type DelUserResp struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelUserResp) Reset()         { *m = DelUserResp{} }
func (m *DelUserResp) String() string { return proto.CompactTextString(m) }
func (*DelUserResp) ProtoMessage()    {}
func (*DelUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{33}
}

func (m *DelUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelUserResp.Unmarshal(m, b)
}
func (m *DelUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelUserResp.Marshal(b, m, deterministic)
}
func (m *DelUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelUserResp.Merge(m, src)
}
func (m *DelUserResp) XXX_Size() int {
	return xxx_messageInfo_DelUserResp.Size(m)
}
func (m *DelUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelUserResp proto.InternalMessageInfo

func (m *DelUserResp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *DelUserResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// 列举用户
type ListUserResp struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	UserList             []string `protobuf:"bytes,3,rep,name=userList,proto3" json:"userList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserResp) Reset()         { *m = ListUserResp{} }
func (m *ListUserResp) String() string { return proto.CompactTextString(m) }
func (*ListUserResp) ProtoMessage()    {}
func (*ListUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d65d1a3c0c8b3d1, []int{34}
}

func (m *ListUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserResp.Unmarshal(m, b)
}
func (m *ListUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserResp.Marshal(b, m, deterministic)
}
func (m *ListUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserResp.Merge(m, src)
}
func (m *ListUserResp) XXX_Size() int {
	return xxx_messageInfo_ListUserResp.Size(m)
}
func (m *ListUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserResp proto.InternalMessageInfo

func (m *ListUserResp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *ListUserResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *ListUserResp) GetUserList() []string {
	if m != nil {
		return m.UserList
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "xgfaceAPI.Empty")
	proto.RegisterType((*Images)(nil), "xgfaceAPI.Images")
	proto.RegisterType((*FaceField)(nil), "xgfaceAPI.FaceField")
	proto.RegisterType((*DetectReq)(nil), "xgfaceAPI.DetectReq")
	proto.RegisterType((*Point)(nil), "xgfaceAPI.Point")
	proto.RegisterType((*Rect)(nil), "xgfaceAPI.Rect")
	proto.RegisterType((*Feature)(nil), "xgfaceAPI.Feature")
	proto.RegisterType((*Features)(nil), "xgfaceAPI.Features")
	proto.RegisterType((*Box)(nil), "xgfaceAPI.Box")
	proto.RegisterType((*Boxs)(nil), "xgfaceAPI.Boxs")
	proto.RegisterType((*Landmark)(nil), "xgfaceAPI.Landmark")
	proto.RegisterType((*Landmarks)(nil), "xgfaceAPI.Landmarks")
	proto.RegisterType((*Body)(nil), "xgfaceAPI.Body")
	proto.RegisterType((*BodyInfo)(nil), "xgfaceAPI.BodyInfo")
	proto.RegisterType((*Face)(nil), "xgfaceAPI.Face")
	proto.RegisterMapType((map[string]int32)(nil), "xgfaceAPI.Face.AttributesEntry")
	proto.RegisterType((*DetectInfo)(nil), "xgfaceAPI.DetectInfo")
	proto.RegisterType((*DetectResp)(nil), "xgfaceAPI.DetectResp")
	proto.RegisterType((*Image)(nil), "xgfaceAPI.Image")
	proto.RegisterType((*ScoreResp)(nil), "xgfaceAPI.ScoreResp")
	proto.RegisterType((*AddFaceReq)(nil), "xgfaceAPI.AddFaceReq")
	proto.RegisterType((*AddFaceResp)(nil), "xgfaceAPI.AddFaceResp")
	proto.RegisterType((*ScanResp)(nil), "xgfaceAPI.ScanResp")
	proto.RegisterType((*ScanFace)(nil), "xgfaceAPI.ScanFace")
	proto.RegisterType((*Result)(nil), "xgfaceAPI.Result")
	proto.RegisterType((*ScanRespEx)(nil), "xgfaceAPI.ScanRespEx")
	proto.RegisterType((*ListFaceReq)(nil), "xgfaceAPI.ListFaceReq")
	proto.RegisterType((*SingleRecord)(nil), "xgfaceAPI.SingleRecord")
	proto.RegisterType((*ListFaceResp)(nil), "xgfaceAPI.ListFaceResp")
	proto.RegisterType((*DelFaceReq)(nil), "xgfaceAPI.DelFaceReq")
	proto.RegisterType((*DelFaceResp)(nil), "xgfaceAPI.DelFaceResp")
	proto.RegisterType((*GetUserInfoReq)(nil), "xgfaceAPI.GetUserInfoReq")
	proto.RegisterType((*GetUserInfoResp)(nil), "xgfaceAPI.GetUserInfoResp")
	proto.RegisterType((*DelUserReq)(nil), "xgfaceAPI.DelUserReq")
	proto.RegisterType((*DelUserResp)(nil), "xgfaceAPI.DelUserResp")
	proto.RegisterType((*ListUserResp)(nil), "xgfaceAPI.ListUserResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// XgfaceAPIServiceClient is the client API for XgfaceAPIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type XgfaceAPIServiceClient interface {
	GetDetectInfo(ctx context.Context, in *DetectReq, opts ...grpc.CallOption) (*DetectResp, error)
	MatchFaces(ctx context.Context, in *Images, opts ...grpc.CallOption) (*ScoreResp, error)
	MatchFacesEx(ctx context.Context, in *Images, opts ...grpc.CallOption) (*ScoreResp, error)
	AddFace(ctx context.Context, in *AddFaceReq, opts ...grpc.CallOption) (*AddFaceResp, error)
	Scan(ctx context.Context, in *Image, opts ...grpc.CallOption) (*ScanResp, error)
	ListFace(ctx context.Context, in *ListFaceReq, opts ...grpc.CallOption) (*ListFaceResp, error)
	ScanEx(ctx context.Context, in *Image, opts ...grpc.CallOption) (*ScanRespEx, error)
	DelFace(ctx context.Context, in *DelFaceReq, opts ...grpc.CallOption) (*DelFaceResp, error)
	DelUser(ctx context.Context, in *DelUserReq, opts ...grpc.CallOption) (*DelUserResp, error)
	ListUser(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListUserResp, error)
	GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
	UpdateFace(ctx context.Context, in *AddFaceReq, opts ...grpc.CallOption) (*AddFaceResp, error)
}

type xgfaceAPIServiceClient struct {
	cc *grpc.ClientConn
}

func NewXgfaceAPIServiceClient(cc *grpc.ClientConn) XgfaceAPIServiceClient {
	return &xgfaceAPIServiceClient{cc}
}

func (c *xgfaceAPIServiceClient) GetDetectInfo(ctx context.Context, in *DetectReq, opts ...grpc.CallOption) (*DetectResp, error) {
	out := new(DetectResp)
	err := c.cc.Invoke(ctx, "/xgfaceAPI.XgfaceAPIService/GetDetectInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xgfaceAPIServiceClient) MatchFaces(ctx context.Context, in *Images, opts ...grpc.CallOption) (*ScoreResp, error) {
	out := new(ScoreResp)
	err := c.cc.Invoke(ctx, "/xgfaceAPI.XgfaceAPIService/MatchFaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xgfaceAPIServiceClient) MatchFacesEx(ctx context.Context, in *Images, opts ...grpc.CallOption) (*ScoreResp, error) {
	out := new(ScoreResp)
	err := c.cc.Invoke(ctx, "/xgfaceAPI.XgfaceAPIService/MatchFacesEx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xgfaceAPIServiceClient) AddFace(ctx context.Context, in *AddFaceReq, opts ...grpc.CallOption) (*AddFaceResp, error) {
	out := new(AddFaceResp)
	err := c.cc.Invoke(ctx, "/xgfaceAPI.XgfaceAPIService/AddFace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xgfaceAPIServiceClient) Scan(ctx context.Context, in *Image, opts ...grpc.CallOption) (*ScanResp, error) {
	out := new(ScanResp)
	err := c.cc.Invoke(ctx, "/xgfaceAPI.XgfaceAPIService/Scan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xgfaceAPIServiceClient) ListFace(ctx context.Context, in *ListFaceReq, opts ...grpc.CallOption) (*ListFaceResp, error) {
	out := new(ListFaceResp)
	err := c.cc.Invoke(ctx, "/xgfaceAPI.XgfaceAPIService/ListFace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xgfaceAPIServiceClient) ScanEx(ctx context.Context, in *Image, opts ...grpc.CallOption) (*ScanRespEx, error) {
	out := new(ScanRespEx)
	err := c.cc.Invoke(ctx, "/xgfaceAPI.XgfaceAPIService/ScanEx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xgfaceAPIServiceClient) DelFace(ctx context.Context, in *DelFaceReq, opts ...grpc.CallOption) (*DelFaceResp, error) {
	out := new(DelFaceResp)
	err := c.cc.Invoke(ctx, "/xgfaceAPI.XgfaceAPIService/DelFace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xgfaceAPIServiceClient) DelUser(ctx context.Context, in *DelUserReq, opts ...grpc.CallOption) (*DelUserResp, error) {
	out := new(DelUserResp)
	err := c.cc.Invoke(ctx, "/xgfaceAPI.XgfaceAPIService/DelUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xgfaceAPIServiceClient) ListUser(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListUserResp, error) {
	out := new(ListUserResp)
	err := c.cc.Invoke(ctx, "/xgfaceAPI.XgfaceAPIService/ListUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xgfaceAPIServiceClient) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	out := new(GetUserInfoResp)
	err := c.cc.Invoke(ctx, "/xgfaceAPI.XgfaceAPIService/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xgfaceAPIServiceClient) UpdateFace(ctx context.Context, in *AddFaceReq, opts ...grpc.CallOption) (*AddFaceResp, error) {
	out := new(AddFaceResp)
	err := c.cc.Invoke(ctx, "/xgfaceAPI.XgfaceAPIService/UpdateFace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XgfaceAPIServiceServer is the server API for XgfaceAPIService service.
type XgfaceAPIServiceServer interface {
	GetDetectInfo(context.Context, *DetectReq) (*DetectResp, error)
	MatchFaces(context.Context, *Images) (*ScoreResp, error)
	MatchFacesEx(context.Context, *Images) (*ScoreResp, error)
	AddFace(context.Context, *AddFaceReq) (*AddFaceResp, error)
	Scan(context.Context, *Image) (*ScanResp, error)
	ListFace(context.Context, *ListFaceReq) (*ListFaceResp, error)
	ScanEx(context.Context, *Image) (*ScanRespEx, error)
	DelFace(context.Context, *DelFaceReq) (*DelFaceResp, error)
	DelUser(context.Context, *DelUserReq) (*DelUserResp, error)
	ListUser(context.Context, *Empty) (*ListUserResp, error)
	GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoResp, error)
	UpdateFace(context.Context, *AddFaceReq) (*AddFaceResp, error)
}

func RegisterXgfaceAPIServiceServer(s *grpc.Server, srv XgfaceAPIServiceServer) {
	s.RegisterService(&_XgfaceAPIService_serviceDesc, srv)
}

func _XgfaceAPIService_GetDetectInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XgfaceAPIServiceServer).GetDetectInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xgfaceAPI.XgfaceAPIService/GetDetectInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XgfaceAPIServiceServer).GetDetectInfo(ctx, req.(*DetectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _XgfaceAPIService_MatchFaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Images)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XgfaceAPIServiceServer).MatchFaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xgfaceAPI.XgfaceAPIService/MatchFaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XgfaceAPIServiceServer).MatchFaces(ctx, req.(*Images))
	}
	return interceptor(ctx, in, info, handler)
}

func _XgfaceAPIService_MatchFacesEx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Images)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XgfaceAPIServiceServer).MatchFacesEx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xgfaceAPI.XgfaceAPIService/MatchFacesEx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XgfaceAPIServiceServer).MatchFacesEx(ctx, req.(*Images))
	}
	return interceptor(ctx, in, info, handler)
}

func _XgfaceAPIService_AddFace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFaceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XgfaceAPIServiceServer).AddFace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xgfaceAPI.XgfaceAPIService/AddFace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XgfaceAPIServiceServer).AddFace(ctx, req.(*AddFaceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _XgfaceAPIService_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Image)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XgfaceAPIServiceServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xgfaceAPI.XgfaceAPIService/Scan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XgfaceAPIServiceServer).Scan(ctx, req.(*Image))
	}
	return interceptor(ctx, in, info, handler)
}

func _XgfaceAPIService_ListFace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFaceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XgfaceAPIServiceServer).ListFace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xgfaceAPI.XgfaceAPIService/ListFace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XgfaceAPIServiceServer).ListFace(ctx, req.(*ListFaceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _XgfaceAPIService_ScanEx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Image)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XgfaceAPIServiceServer).ScanEx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xgfaceAPI.XgfaceAPIService/ScanEx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XgfaceAPIServiceServer).ScanEx(ctx, req.(*Image))
	}
	return interceptor(ctx, in, info, handler)
}

func _XgfaceAPIService_DelFace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelFaceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XgfaceAPIServiceServer).DelFace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xgfaceAPI.XgfaceAPIService/DelFace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XgfaceAPIServiceServer).DelFace(ctx, req.(*DelFaceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _XgfaceAPIService_DelUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XgfaceAPIServiceServer).DelUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xgfaceAPI.XgfaceAPIService/DelUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XgfaceAPIServiceServer).DelUser(ctx, req.(*DelUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _XgfaceAPIService_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XgfaceAPIServiceServer).ListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xgfaceAPI.XgfaceAPIService/ListUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XgfaceAPIServiceServer).ListUser(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _XgfaceAPIService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XgfaceAPIServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xgfaceAPI.XgfaceAPIService/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XgfaceAPIServiceServer).GetUserInfo(ctx, req.(*GetUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _XgfaceAPIService_UpdateFace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFaceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XgfaceAPIServiceServer).UpdateFace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xgfaceAPI.XgfaceAPIService/UpdateFace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XgfaceAPIServiceServer).UpdateFace(ctx, req.(*AddFaceReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _XgfaceAPIService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "xgfaceAPI.XgfaceAPIService",
	HandlerType: (*XgfaceAPIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDetectInfo",
			Handler:    _XgfaceAPIService_GetDetectInfo_Handler,
		},
		{
			MethodName: "MatchFaces",
			Handler:    _XgfaceAPIService_MatchFaces_Handler,
		},
		{
			MethodName: "MatchFacesEx",
			Handler:    _XgfaceAPIService_MatchFacesEx_Handler,
		},
		{
			MethodName: "AddFace",
			Handler:    _XgfaceAPIService_AddFace_Handler,
		},
		{
			MethodName: "Scan",
			Handler:    _XgfaceAPIService_Scan_Handler,
		},
		{
			MethodName: "ListFace",
			Handler:    _XgfaceAPIService_ListFace_Handler,
		},
		{
			MethodName: "ScanEx",
			Handler:    _XgfaceAPIService_ScanEx_Handler,
		},
		{
			MethodName: "DelFace",
			Handler:    _XgfaceAPIService_DelFace_Handler,
		},
		{
			MethodName: "DelUser",
			Handler:    _XgfaceAPIService_DelUser_Handler,
		},
		{
			MethodName: "ListUser",
			Handler:    _XgfaceAPIService_ListUser_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _XgfaceAPIService_GetUserInfo_Handler,
		},
		{
			MethodName: "UpdateFace",
			Handler:    _XgfaceAPIService_UpdateFace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "faceAPI.proto",
}

func init() { proto.RegisterFile("faceAPI.proto", fileDescriptor_1d65d1a3c0c8b3d1) }

var fileDescriptor_1d65d1a3c0c8b3d1 = []byte{
	// 1324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xed, 0x6e, 0xdb, 0xd4,
	0x1b, 0x5f, 0xe2, 0x38, 0x4d, 0x9e, 0x74, 0x6d, 0x77, 0xfe, 0xdd, 0xe6, 0x7f, 0x40, 0xb0, 0x1d,
	0x36, 0xa9, 0x9a, 0x50, 0xa7, 0x66, 0x20, 0xc6, 0xa4, 0x6d, 0x5a, 0x59, 0x3b, 0x15, 0xad, 0xa8,
	0x3a, 0xdd, 0xc4, 0x90, 0x90, 0x2a, 0xc7, 0x3e, 0x49, 0xcd, 0x9c, 0x38, 0xb5, 0x4f, 0xb6, 0x44,
	0xdc, 0x00, 0xd7, 0x81, 0xc4, 0x4d, 0xf0, 0x89, 0xbb, 0xe0, 0x23, 0xb7, 0x82, 0x9e, 0xf3, 0x62,
	0x1f, 0x7b, 0x69, 0x10, 0x11, 0xdf, 0xfc, 0xbc, 0xff, 0x9e, 0xd7, 0x93, 0xc0, 0xd5, 0x81, 0x1f,
	0xf0, 0x67, 0x27, 0x47, 0xbb, 0x93, 0x34, 0x11, 0x09, 0x69, 0xcf, 0x86, 0x9a, 0x41, 0xd7, 0xc0,
	0x3d, 0x18, 0x4d, 0xc4, 0x9c, 0x3e, 0x84, 0xe6, 0xd1, 0xc8, 0x1f, 0xf2, 0x8c, 0xdc, 0x80, 0x66,
	0x84, 0x5f, 0x7b, 0x5e, 0xed, 0x56, 0x6d, 0xa7, 0xcd, 0x34, 0x95, 0xf3, 0x7b, 0x5e, 0xdd, 0xe2,
	0xf7, 0xe8, 0xcf, 0xd0, 0x3e, 0xf4, 0x03, 0x7e, 0x18, 0xf1, 0x38, 0x24, 0x5d, 0x68, 0xc5, 0xfe,
	0x38, 0x1c, 0xf9, 0xe9, 0x5b, 0x69, 0xee, 0xb2, 0x9c, 0x26, 0x9f, 0x00, 0xf8, 0x42, 0xa4, 0x51,
	0x7f, 0x2a, 0x78, 0x26, 0x9d, 0xb8, 0xcc, 0xe2, 0x10, 0x0f, 0xd6, 0x2e, 0xa6, 0x7e, 0x1c, 0x89,
	0xb9, 0xe7, 0x48, 0xa1, 0x21, 0x51, 0x32, 0xe0, 0xbe, 0x98, 0xa6, 0xdc, 0x6b, 0x28, 0x89, 0x26,
	0xe9, 0xf7, 0xd0, 0x7e, 0xce, 0x05, 0x0f, 0x04, 0xe3, 0x17, 0xa4, 0x07, 0x6d, 0xcc, 0x6b, 0x80,
	0x48, 0x64, 0xf4, 0x4e, 0x6f, 0x7b, 0x37, 0xcf, 0x75, 0x37, 0x47, 0xc9, 0x0a, 0xb5, 0x3c, 0x2b,
	0x04, 0xe4, 0xe4, 0x59, 0x65, 0xf4, 0x18, 0xdc, 0x93, 0x24, 0x1a, 0x0b, 0x72, 0x1b, 0xd6, 0x83,
	0x24, 0x49, 0xc3, 0x68, 0xec, 0x0b, 0x7e, 0x36, 0x93, 0x7e, 0xeb, 0xac, 0x53, 0xf0, 0xde, 0x54,
	0x54, 0xe6, 0x32, 0xb5, 0x92, 0xca, 0x0f, 0xf4, 0x0b, 0x68, 0x30, 0x1e, 0x08, 0xb2, 0x0d, 0xee,
	0xfb, 0x28, 0x14, 0xe7, 0xda, 0x8d, 0x22, 0x10, 0xc4, 0x39, 0x8f, 0x86, 0xe7, 0x42, 0x9b, 0x6a,
	0x8a, 0xde, 0x86, 0xb5, 0x43, 0x95, 0x28, 0xaa, 0xbc, 0xf3, 0xe3, 0x29, 0xcf, 0xbc, 0xda, 0x2d,
	0x07, 0x55, 0x14, 0x45, 0x1f, 0x41, 0x4b, 0xab, 0x64, 0x64, 0x17, 0x5a, 0xba, 0x2e, 0x4a, 0xab,
	0xd3, 0x23, 0x76, 0xfa, 0x4a, 0xc4, 0x72, 0x1d, 0xfa, 0x13, 0x38, 0xfb, 0xc9, 0x8c, 0xec, 0x40,
	0x33, 0xe0, 0x63, 0xc1, 0x53, 0x5d, 0xb3, 0x2d, 0xcb, 0x48, 0xd6, 0x80, 0x69, 0x39, 0xf9, 0x0c,
	0x1a, 0x29, 0x0f, 0x14, 0xca, 0x4e, 0x6f, 0xd3, 0xd2, 0xc3, 0xe4, 0x98, 0x14, 0x62, 0x8a, 0x59,
	0x90, 0xa4, 0x5c, 0x36, 0xb1, 0xce, 0x14, 0x41, 0xef, 0x41, 0x63, 0x3f, 0x99, 0x65, 0x84, 0x42,
	0xa3, 0x9f, 0xcc, 0x0c, 0xbe, 0x0d, 0xcb, 0xc5, 0x7e, 0x32, 0x63, 0x52, 0x46, 0xbf, 0x85, 0xd6,
	0x4b, 0x33, 0x34, 0x3b, 0xd0, 0x9c, 0x20, 0x06, 0x63, 0xb1, 0x00, 0x9c, 0x92, 0x17, 0x71, 0xeb,
	0x76, 0xdc, 0x27, 0xd0, 0x36, 0xbe, 0x32, 0xb2, 0x07, 0x6d, 0x33, 0x8d, 0xc6, 0xdf, 0xff, 0x2c,
	0x7f, 0x46, 0x91, 0x15, 0x5a, 0x74, 0x07, 0x71, 0x87, 0x73, 0x72, 0x0b, 0x9c, 0x7e, 0x32, 0xd3,
	0x15, 0xaa, 0xc2, 0x46, 0x11, 0xdd, 0x83, 0x16, 0x6a, 0x1e, 0x8d, 0x07, 0x09, 0xb9, 0x0b, 0x6e,
	0x3f, 0x09, 0xe7, 0x26, 0xc8, 0x66, 0x49, 0x3f, 0x9c, 0x33, 0x25, 0xa5, 0x7f, 0x3a, 0xd0, 0xc0,
	0xa9, 0xfc, 0x67, 0xef, 0xe4, 0xbe, 0xb5, 0x58, 0xaa, 0xfc, 0x0b, 0x91, 0x17, 0xdb, 0xf6, 0x79,
	0xb1, 0x33, 0x8e, 0xd4, 0x5f, 0x34, 0x0b, 0x46, 0x85, 0x3c, 0x2d, 0xed, 0x66, 0x43, 0xa2, 0xfe,
	0xb4, 0xb2, 0x3b, 0xbb, 0xcf, 0x72, 0x8d, 0x83, 0xb1, 0x48, 0xe7, 0xa5, 0xe5, 0xdd, 0x06, 0x77,
	0x12, 0x89, 0xe0, 0xdc, 0x73, 0x55, 0xf5, 0x25, 0x41, 0xb6, 0xc0, 0x99, 0xfb, 0xef, 0xbd, 0xa6,
	0xe4, 0xe1, 0x27, 0x21, 0xd0, 0x48, 0x93, 0x38, 0xf6, 0xd6, 0x24, 0x4b, 0x7e, 0x93, 0x3b, 0xb0,
	0x31, 0x8c, 0x93, 0xbe, 0x1f, 0x9f, 0x45, 0xd9, 0x19, 0x46, 0xf4, 0x5a, 0x52, 0xba, 0xae, 0xb8,
	0x47, 0x99, 0xac, 0xd1, 0x3d, 0xb8, 0xa6, 0xb5, 0x06, 0x69, 0x32, 0x16, 0x4a, 0xb1, 0x2d, 0x15,
	0x37, 0x95, 0xe0, 0x10, 0xf9, 0x52, 0x97, 0xc2, 0xd5, 0x38, 0x09, 0x2c, 0x87, 0xa0, 0x56, 0x52,
	0x32, 0xb5, 0xbf, 0x8f, 0xd5, 0xb5, 0x78, 0x95, 0xbc, 0xe5, 0x63, 0xaf, 0x23, 0x4f, 0x5a, 0xc1,
	0xe8, 0x3e, 0x86, 0xcd, 0x4a, 0xba, 0x98, 0xcc, 0x5b, 0x3e, 0xd7, 0x57, 0x11, 0x3f, 0x31, 0x69,
	0xb9, 0x86, 0xfa, 0x98, 0x29, 0xe2, 0x51, 0xfd, 0x61, 0x8d, 0x1e, 0x03, 0xa8, 0xbb, 0x24, 0xc7,
	0x01, 0xef, 0x97, 0x1f, 0xf0, 0xef, 0xa6, 0x23, 0x7d, 0x14, 0x0d, 0x89, 0x83, 0x82, 0x9f, 0xea,
	0xfa, 0x94, 0x07, 0x05, 0x41, 0x32, 0x25, 0xa5, 0x53, 0xe3, 0x8e, 0xf1, 0x6c, 0x82, 0xee, 0x78,
	0x9a, 0x7e, 0x93, 0x84, 0xdc, 0xb8, 0xd3, 0x24, 0x5e, 0x09, 0x9e, 0xa6, 0xc7, 0xd9, 0xd0, 0xdc,
	0x68, 0x45, 0x91, 0x2f, 0x01, 0xc2, 0x1c, 0x8e, 0x9e, 0x87, 0xeb, 0x56, 0xac, 0x02, 0x2b, 0xb3,
	0x14, 0xe9, 0x47, 0xe0, 0xca, 0x47, 0x01, 0xbb, 0x16, 0xfa, 0xc2, 0xd7, 0xb9, 0xcb, 0x6f, 0x7a,
	0x0a, 0xed, 0x53, 0x5c, 0xb1, 0x15, 0x21, 0x2d, 0x3e, 0x13, 0xaf, 0x00, 0x9e, 0x85, 0xa1, 0x4c,
	0x9d, 0x5f, 0x2c, 0x0a, 0x8b, 0xfe, 0xa6, 0x19, 0x4f, 0x8f, 0x9e, 0x1b, 0x7f, 0x8a, 0xc2, 0x97,
	0x47, 0x7e, 0x99, 0x04, 0xdb, 0x2c, 0xa7, 0xe9, 0x6f, 0x35, 0xe8, 0xe4, 0x6e, 0x57, 0x42, 0x7b,
	0x0f, 0x5a, 0x38, 0x3b, 0x22, 0x4a, 0xc6, 0xba, 0x7c, 0xd5, 0x2d, 0xcd, 0xe5, 0xe5, 0xc1, 0x6a,
	0x54, 0x06, 0x0b, 0x71, 0x46, 0xa3, 0xa1, 0x12, 0xba, 0x0a, 0xa7, 0xa1, 0xe9, 0x1f, 0x35, 0x68,
	0x9d, 0x06, 0xfe, 0xf8, 0xbf, 0x2c, 0x69, 0x29, 0x60, 0xa3, 0x1c, 0xb0, 0x0c, 0xd5, 0xad, 0x42,
	0x2d, 0x4a, 0xdd, 0xbc, 0xb4, 0xd4, 0x6b, 0x95, 0x52, 0xff, 0xae, 0x53, 0xf8, 0x70, 0xc5, 0x6a,
	0x55, 0xf7, 0x0b, 0x0f, 0x76, 0x09, 0xae, 0x53, 0x81, 0x5b, 0x00, 0x6a, 0x5c, 0x0a, 0xc8, 0x2d,
	0x03, 0x2a, 0x75, 0xae, 0xb9, 0xbc, 0x73, 0xf4, 0x14, 0x9a, 0x8c, 0x67, 0xd3, 0x58, 0x2c, 0xd9,
	0xd8, 0xfb, 0xd0, 0xc2, 0xcf, 0x97, 0x51, 0x26, 0xf4, 0xd2, 0xda, 0x87, 0xd8, 0xa4, 0xce, 0x72,
	0x25, 0x7a, 0x01, 0x60, 0x7a, 0x7a, 0x30, 0x5b, 0xa1, 0xab, 0x7b, 0x00, 0x99, 0xb2, 0x9f, 0xc6,
	0x42, 0x0f, 0xdf, 0xb5, 0xd2, 0xd3, 0x8b, 0x02, 0x66, 0x29, 0xd1, 0xbb, 0xd0, 0xc1, 0xd0, 0x66,
	0x8d, 0x8a, 0xb2, 0xd5, 0xec, 0xb2, 0xd1, 0x5f, 0x6a, 0xb0, 0x7e, 0x1a, 0x8d, 0x87, 0x31, 0x67,
	0x3c, 0x48, 0xd2, 0x10, 0x7f, 0xa1, 0x05, 0x29, 0xf7, 0x05, 0x7f, 0x15, 0x8d, 0x14, 0x3e, 0x87,
	0x59, 0x1c, 0x94, 0x4f, 0x27, 0xa1, 0x91, 0xd7, 0x95, 0xbc, 0xe0, 0x2c, 0xed, 0xdd, 0xd2, 0xad,
	0xa0, 0x73, 0x58, 0x2f, 0x10, 0xaf, 0x34, 0xfc, 0x5f, 0x01, 0x0c, 0xa4, 0x35, 0x66, 0xe2, 0x39,
	0xb2, 0x33, 0x37, 0xed, 0xce, 0x58, 0x89, 0x32, 0x4b, 0x95, 0xee, 0xe3, 0x6d, 0x8d, 0x4d, 0xad,
	0x96, 0x8f, 0xec, 0x25, 0xc7, 0x87, 0x3e, 0x85, 0x4e, 0xee, 0x63, 0x15, 0xf4, 0x74, 0x07, 0x36,
	0x5e, 0x70, 0xf1, 0x5a, 0x0f, 0xed, 0xb2, 0xa6, 0x9d, 0xc1, 0x66, 0x49, 0x73, 0xa5, 0x62, 0x95,
	0x8f, 0xa5, 0x53, 0xda, 0xe0, 0x3b, 0xb2, 0x1e, 0x18, 0x60, 0x19, 0x0c, 0x95, 0xb1, 0xd2, 0x5a,
	0x29, 0xe3, 0x1f, 0x55, 0xc7, 0x57, 0xf7, 0x60, 0x92, 0x90, 0x9b, 0x68, 0x25, 0x81, 0x74, 0xef,
	0x2f, 0x17, 0xb6, 0xde, 0x98, 0xde, 0x9f, 0xf2, 0xf4, 0x5d, 0x14, 0x70, 0xf2, 0x04, 0xae, 0xbe,
	0xe0, 0xc2, 0x7a, 0x97, 0xb7, 0x3f, 0x78, 0x02, 0x19, 0xbf, 0xe8, 0x5e, 0x5f, 0xc0, 0xcd, 0x26,
	0xf4, 0x0a, 0x8e, 0xd8, 0xb1, 0x2f, 0x82, 0x73, 0xec, 0x73, 0x46, 0xec, 0x1d, 0x54, 0x7f, 0x9d,
	0xba, 0xdb, 0xa5, 0x4b, 0xa0, 0xdf, 0x46, 0x7a, 0x85, 0x7c, 0x0d, 0xeb, 0x85, 0xe1, 0xc1, 0xec,
	0xdf, 0x98, 0x3e, 0x82, 0x35, 0xfd, 0x72, 0x11, 0x1b, 0x57, 0xf1, 0x48, 0x76, 0x6f, 0x2c, 0x62,
	0x4b, 0xdb, 0xfb, 0xd0, 0xc0, 0xcb, 0x43, 0xb6, 0xaa, 0xe1, 0xba, 0xd5, 0x93, 0xa5, 0x0d, 0x1e,
	0x43, 0xcb, 0x6c, 0x21, 0xb1, 0xdd, 0x5a, 0xc7, 0xa4, 0x7b, 0x73, 0x21, 0x5f, 0x9a, 0x3f, 0x80,
	0x26, 0x3a, 0x3b, 0x98, 0x2d, 0x88, 0x78, 0x7d, 0x41, 0xc4, 0x83, 0x99, 0x4a, 0x50, 0xaf, 0x0e,
	0x29, 0x17, 0x3e, 0x5e, 0x94, 0xa0, 0xb5, 0x65, 0xb9, 0x2d, 0x8e, 0x50, 0xd5, 0x56, 0x8f, 0x6f,
	0xd5, 0xd6, 0x4c, 0x9b, 0x6c, 0x66, 0xcb, 0xcc, 0x5f, 0x09, 0xae, 0xfc, 0x3b, 0xfc, 0x41, 0x96,
	0x96, 0xe1, 0x21, 0x74, 0xac, 0x05, 0x24, 0xff, 0xb7, 0x34, 0xcb, 0x2b, 0xdc, 0xed, 0x5e, 0x26,
	0xd2, 0xc5, 0x86, 0xd7, 0xf2, 0x74, 0xae, 0xd4, 0xdc, 0xfd, 0x1e, 0x78, 0x41, 0x32, 0xda, 0x9d,
	0x0d, 0xd3, 0xa4, 0x9f, 0x88, 0x28, 0xc8, 0x0a, 0xcd, 0xfd, 0x8d, 0x7c, 0xf4, 0x4f, 0xf0, 0x0f,
	0xff, 0x49, 0xed, 0xd7, 0xba, 0xf3, 0xe6, 0xc5, 0x61, 0xbf, 0x29, 0xff, 0xff, 0x3f, 0xf8, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0x09, 0x47, 0x6b, 0xca, 0x10, 0x10, 0x00, 0x00,
}
